version: 2
updates:
  - package-ecosystem: "npm"
    prefix: "bump: "
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    prefix: "bump: "
    directory: "/"
    schedule:
      interval: "monthly"